"use client";
import "./refresh.css";
import { useMemo, useState } from "react";
import { LayoutDashboard, Inbox, ShieldCheck, Database, History, GitCompareArrows, FileText, Users, Search, CheckCircle2, AlertTriangle, XCircle, Eye, CalendarClock, Upload, Download, ChevronRight, ChevronDown, ChevronUp, GitBranch, LockKeyhole, RotateCcw, UserPlus, Pencil, Trash2, TrendingUp, TrendingDown, BarChart3 } from "lucide-react";

type View="inicio"|"bandeja"|"validacion"|"matriz"|"historico"|"conciliacion"|"layout"|"admin";
type BonusStatus="Cumple"|"Revisión"|"Falta evidencia"|"Aprobado"|"Rechazado";
type Bonus={id:string;employee:string;name:string;bonus:string;client:string;site:string;requested:number;calculated:number;support:boolean;status:BonusStatus;days:number;matched:number;source:"SharePoint"|"Correo Pasadena";exception?:boolean};
type Role="Super Admin"|"Admin"|"Usuario";
type DemoUser={id:number;name:string;role:Role};
type CompareRange="Mes anterior"|"Trimestre"|"Semestre"|"Año";
// UX Semana 38 publicado en GitHub Pages v2
const bonuses:Bonus[]=[
{id:"B-038-001",employee:"274816",name:"Julio César Martínez",bonus:"Ayuda de transporte",client:"Henkel",site:"Salamanca",requested:600,calculated:500,support:true,status:"Revisión",days:5,matched:4,source:"SharePoint"},
{id:"B-038-002",employee:"258760",name:"Omar Espinoza Díaz",bonus:"Asistencia",client:"Operación semanal",site:"Morelia",requested:900,calculated:900,support:true,status:"Cumple",days:5,matched:5,source:"SharePoint"},
{id:"B-038-003",employee:"253333",name:"Karla Vibriezca",bonus:"Acciones destacadas",client:"Cliente demo",site:"CDMX",requested:1200,calculated:1200,support:false,status:"Falta evidencia",days:0,matched:0,source:"Correo Pasadena"},
{id:"B-038-004",employee:"261904",name:"Mariana Reyes",bonus:"Ayuda de transporte",client:"BBVA",site:"Saltillo",requested:500,calculated:540,support:true,status:"Revisión",days:5,matched:5,source:"SharePoint"},
];
const money=(n:number)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0}).format(n);
const comparisonData:Record<CompareRange,{reference:string;amount:number;previousAmount:number;movements:number;previousMovements:number;approved:number;previousApproved:number;categories:{name:string;current:number;previous:number}[]}>= {
 "Mes anterior":{reference:"Agosto 2026",amount:428500,previousAmount:391200,movements:236,previousMovements:218,approved:218,previousApproved:201,categories:[{name:"Ayuda de transporte",current:126400,previous:118900},{name:"Asistencia",current:174300,previous:160800},{name:"Acciones destacadas",current:127800,previous:111500}]},
 "Trimestre":{reference:"Abr–Jun 2026",amount:1248600,previousAmount:1174200,movements:684,previousMovements:641,approved:638,previousApproved:602,categories:[{name:"Ayuda de transporte",current:362700,previous:345100},{name:"Asistencia",current:514800,previous:482600},{name:"Acciones destacadas",current:371100,previous:346500}]},
 "Semestre":{reference:"Ene–Jun 2026",amount:2487300,previousAmount:2294100,movements:1372,previousMovements:1294,approved:1281,previousApproved:1207,categories:[{name:"Ayuda de transporte",current:721400,previous:674300},{name:"Asistencia",current:1032900,previous:948200},{name:"Acciones destacadas",current:733000,previous:671600}]},
 "Año":{reference:"Año 2025",amount:4968400,previousAmount:4512900,movements:2741,previousMovements:2538,approved:2560,previousApproved:2374,categories:[{name:"Ayuda de transporte",current:1438200,previous:1324800},{name:"Asistencia",current:2064100,previous:1879300},{name:"Acciones destacadas",current:1466100,previous:1308800}]}
};
const nav=[["inicio","Resumen",LayoutDashboard],["bandeja","Bandeja de bonos",Inbox],["validacion","Centro de validación",ShieldCheck],["matriz","Matriz de bonos",Database],["historico","Histórico",History],["conciliacion","Conciliación",GitCompareArrows],["layout","Layout Human",FileText],["admin","Administración",Users]] as const;
export default function Page(){
 const [view,setView]=useState<View>("inicio"); const [records,setRecords]=useState<Bonus[]>(bonuses); const [selected,setSelected]=useState<Bonus>(bonuses[0]); const [notice,setNotice]=useState(""); const [evidence,setEvidence]=useState<"asistencia"|"matriz"|"soporte"|null>(null);
 const [homeTab,setHomeTab]=useState<"resumen"|"comparativos">("resumen"); const [compareRange,setCompareRange]=useState<CompareRange>("Mes anterior"); const [comparePeriod,setComparePeriod]=useState("Septiembre 2026");
 const [role,setRole]=useState<Role>("Super Admin"); const [closed,setClosed]=useState(false); const [extension,setExtension]=useState(1); const [expanded,setExpanded]=useState<string[]>(["Ayuda de transporte"]); const [inboxExpanded,setInboxExpanded]=useState<string[]>(["Ayuda de transporte","Asistencia","Acciones destacadas"]); const [inboxQuery,setInboxQuery]=useState(""); const [inboxStatus,setInboxStatus]=useState("Todos"); const [justification,setJustification]=useState("");
 const [users,setUsers]=useState<DemoUser[]>([{id:1,name:"Frances Fernández",role:"Super Admin"},{id:2,name:"Dirección Finanzas",role:"Super Admin"},{id:3,name:"Miriam",role:"Admin"},{id:4,name:"Lizbeth",role:"Admin"},{id:5,name:"Usuario ABM 01",role:"Usuario"}]);
 const totals=useMemo(()=>({amount:records.reduce((a,b)=>a+b.requested,0),review:records.filter(b=>!["Cumple","Aprobado"].includes(b.status)).length,support:records.filter(b=>b.support||b.exception).length}),[records]);
 const groups=useMemo(()=>records.reduce<Record<string,Bonus[]>>((acc,b)=>{(acc[b.bonus]??=[]).push(b);return acc},{}),[records]); const allResolved=records.every(b=>["Cumple","Aprobado","Rechazado"].includes(b.status));
 const inboxGroups=useMemo(()=>records.filter(item=>{const term=inboxQuery.trim().toLowerCase();const matchesText=!term||[item.name,item.employee,item.bonus,item.client,item.site].some(value=>value.toLowerCase().includes(term));const matchesStatus=inboxStatus==="Todos"||item.status===inboxStatus;return matchesText&&matchesStatus}).reduce<Record<string,Bonus[]>>((acc,item)=>{(acc[item.bonus]??=[]).push(item);return acc},{}),[records,inboxQuery,inboxStatus]);
 const comparison=comparisonData[compareRange]; const amountDelta=(comparison.amount-comparison.previousAmount)/comparison.previousAmount*100; const movementDelta=(comparison.movements-comparison.previousMovements)/comparison.previousMovements*100;
 const decide=(status:BonusStatus,exception=false)=>{const next={...selected,status,exception};setRecords(current=>current.map(item=>item.id===selected.id?next:item));setSelected(next);setNotice(status==="Aprobado"?"Movimiento aprobado y registrado en la bitácora.":status==="Rechazado"?"Movimiento devuelto a ABM; el original permanece protegido.":"Ajuste guardado para revisión.")};
 const go=(v:View)=>{setView(v);setNotice("");setEvidence(null)};
 return <main className="shell">
  <aside className="sidebar"><div className="brand"><div className="mark">IC</div><div><strong>Bonos Nómina</strong><small>INTER-CON · México</small></div></div>
   <nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?"active":""} onClick={()=>go(id as View)}><Icon size={18}/>{label}</button>)}</nav>
   <div className="user"><div className="avatar">FF</div><div><strong>Frances Fernández</strong><small>{role} · Demo UX</small></div></div>
  </aside>
  <section className="workspace">
   <header className="top"><div><small>Automatización de Bonos</small><h1>{nav.find(n=>n[0]===view)?.[1]}</h1></div><div className="top-actions"><label className="role-switch">Vista<select value={role} onChange={e=>setRole(e.target.value as Role)}><option>Super Admin</option><option>Admin</option><option>Usuario</option></select></label><div className="period"><CalendarClock size={18}/><span><b>SEM II 38 · v{extension}.0</b><small>{closed?"Ciclo cerrado":"Cierre lunes · 14:00"}</small></span></div></div></header>
   {notice&&<div className="notice">{notice}</div>}
   {view==="inicio"&&<section className="screen">
    <div className="home-tabs" role="tablist"><button className={homeTab==="resumen"?"active":""} onClick={()=>setHomeTab("resumen")}><LayoutDashboard size={17}/> Resumen</button><button className={homeTab==="comparativos"?"active":""} onClick={()=>setHomeTab("comparativos")}><BarChart3 size={17}/> Comparativos</button></div>
    {homeTab==="resumen"?<>
     <div className="hero"><div><span className="eyebrow">PERIODO ACTIVO</span><h2>Semana 38 · Validación de bonos</h2><p>Prototipo funcional para validar el flujo antes de conectar ICON, correo, SharePoint y Human.</p></div><button onClick={()=>go("bandeja")}>Abrir bandeja <ChevronRight size={18}/></button></div>
     <div className="kpis"><Kpi label="Movimientos" value="236" sub="Layout semanal"/><Kpi label="Importe demo" value={money(totals.amount)} sub="Muestra UX"/><Kpi label="Requieren revisión" value={totals.review} sub="Casos demo"/><Kpi label="Con respaldo" value={totals.support+"/4"} sub="Documentación"/></div>
     <div className="grid2"><Card title="Estado del periodo"><div className="steps"><Step ok text="Carga recibida"/><Step ok text="Entregado a Nóminas"/><Step warn text="Validación en curso"/><Step text="Layout Human"/><Step text="Cierre"/></div></Card><Card title="Alertas operativas"><AlertTriangle/><p><b>2 movimientos</b> presentan diferencias entre lo solicitado y la evidencia.</p><p><b>1 movimiento</b> no cuenta con respaldo.</p><button className="link" onClick={()=>go("validacion")}>Ir al Centro de Validación</button></Card></div>
    </>:<>
     <div className="comparison-command"><div><span className="eyebrow">ANÁLISIS DE BONOS</span><h2>Comparativos por periodo</h2><p>Compara importe, movimientos y resultados contra periodos anteriores.</p></div><label>Periodo base<select value={comparePeriod} onChange={e=>setComparePeriod(e.target.value)}><option>Septiembre 2026</option><option>Agosto 2026</option><option>Julio 2026</option><option>Junio 2026</option></select></label></div>
     <div className="range-tabs">{(["Mes anterior","Trimestre","Semestre","Año"] as CompareRange[]).map(range=><button key={range} className={compareRange===range?"active":""} onClick={()=>setCompareRange(range)}>{range}</button>)}</div>
     <div className="comparison-context"><span><b>{comparePeriod}</b> contra <b>{comparison.reference}</b></span><em>DATOS DEMO</em></div>
     <div className="kpis comparison-kpis"><Kpi label="Importe periodo base" value={money(comparison.amount)} sub={comparePeriod}/><Kpi label="Importe comparado" value={money(comparison.previousAmount)} sub={comparison.reference}/><Kpi label="Variación de importe" value={`${amountDelta>=0?"+":""}${amountDelta.toFixed(1)}%`} sub={money(comparison.amount-comparison.previousAmount)}/><Kpi label="Movimientos" value={comparison.movements} sub={`${movementDelta>=0?"+":""}${movementDelta.toFixed(1)}% vs. comparado`}/></div>
     <div className="comparison-grid"><Card title="Importe por tipo de bono"><div className="chart-legend"><span><i className="current-dot"/> {comparePeriod}</span><span><i className="previous-dot"/> {comparison.reference}</span></div><div className="category-comparison">{comparison.categories.map(category=>{const max=Math.max(...comparison.categories.flatMap(item=>[item.current,item.previous]));const delta=(category.current-category.previous)/category.previous*100;return <div className="category-row" key={category.name}><div className="category-label"><b>{category.name}</b><span className={delta>=0?"positive":"negative"}>{delta>=0?<TrendingUp/>:<TrendingDown/>}{delta>=0?"+":""}{delta.toFixed(1)}%</span></div><div className="bar-line"><div className="bar current" style={{width:`${category.current/max*100}%`}}><span>{money(category.current)}</span></div></div><div className="bar-line"><div className="bar previous" style={{width:`${category.previous/max*100}%`}}><span>{money(category.previous)}</span></div></div></div>})}</div></Card><Card title="Indicadores del comparativo"><div className="comparison-metrics"><Metric label="Movimientos actuales" value={String(comparison.movements)}/><Metric label="Movimientos comparados" value={String(comparison.previousMovements)}/><Metric label="Aceptados actuales" value={String(comparison.approved)}/><Metric label="Aceptados comparados" value={String(comparison.previousApproved)}/></div><div className="variance-callout"><TrendingUp/><div><b>{amountDelta.toFixed(1)}% de crecimiento</b><p>El importe aumentó {money(comparison.amount-comparison.previousAmount)} en el corte seleccionado.</p></div></div><button className="secondary comparison-export" onClick={()=>setNotice(`Comparativo ${comparePeriod} vs. ${comparison.reference} preparado para exportación.`)}><Download/> Exportar comparativo</button></Card></div>
    </>}
   </section>}
   {view==="bandeja"&&<section className="screen"><Head title="Bandeja Semana 38" text="Lo entregado a Nóminas queda congelado para revisión; los ajustes posteriores requieren extensión."/><div className="frozen-banner"><LockKeyhole size={18}/><span><b>Versión original protegida</b><small>Los rechazos generan una extensión para ABM sin modificar la entrega original.</small></span><em>Ronda {extension}</em></div><div className="toolbar inbox-toolbar"><div className="search"><Search size={17}/><input value={inboxQuery} onChange={e=>setInboxQuery(e.target.value)} placeholder="Empleado, bono, cliente o instalación"/></div><label className="result-filter">Resultado<select value={inboxStatus} onChange={e=>setInboxStatus(e.target.value)}><option>Todos</option><option>Cumple</option><option>Revisión</option><option>Falta evidencia</option><option>Aprobado</option><option>Rechazado</option></select></label>{role!=="Usuario"&&<button className="secondary" onClick={()=>{setExtension(v=>v+1);setNotice("Extensión creada con trazabilidad de cambios.")}}><GitBranch/> Crear extensión</button>}<button onClick={()=>setNotice("Periodo entregado a Nóminas; la versión quedó congelada.")}>Entregar a Nóminas</button></div><div className="inbox-groups">{Object.entries(inboxGroups).map(([name,items])=><section className="inbox-group" key={name}><button className="inbox-group-head" onClick={()=>setInboxExpanded(current=>current.includes(name)?current.filter(item=>item!==name):[...current,name])}><span><b>{name}</b><small>{items.length} movimientos · {items.filter(item=>!["Cumple","Aprobado"].includes(item.status)).length} por revisar · {money(items.reduce((sum,item)=>sum+item.requested,0))}</small></span><span className="group-status"><Status s={items.some(item=>!["Cumple","Aprobado"].includes(item.status))?"Revisión":"Cumple"}/>{inboxExpanded.includes(name)?<ChevronUp/>:<ChevronDown/>}</span></button>{inboxExpanded.includes(name)&&<BonusTable data={items} open={(b)=>{setSelected(b);go("validacion")}}/>}</section>)}{!Object.keys(inboxGroups).length&&<div className="empty-filter"><Search/><b>Sin resultados</b><span>Prueba cambiando el texto o el filtro de resultado.</span></div>}</div></section>}
   {view==="validacion"&&<section className="screen"><Head title="Centro de Validación" text="Solicitud, matriz, asignación, asistencia y respaldo en una sola decisión."/>
    <div className="validation">
     <div className="case-list grouped">{Object.entries(groups).map(([name,items])=><section className="case-group" key={name}><button className="group-title" onClick={()=>setExpanded(current=>current.includes(name)?current.filter(item=>item!==name):[...current,name])}><span><b>{name}</b><small>{items.length} movimientos · {items.filter(item=>!["Cumple","Aprobado","Rechazado"].includes(item.status)).length} por revisar</small></span>{expanded.includes(name)?<ChevronUp/>:<ChevronDown/>}</button>{expanded.includes(name)&&items.map(b=><button className={selected.id===b.id?"case active":"case"} onClick={()=>setSelected(b)} key={b.id}><span><b>{b.name}</b><small>{b.employee} · {b.source}</small></span><Status s={b.status}/></button>)}</section>)}</div>
     <div className="case-detail"><div className="case-head"><div><span className="eyebrow">{selected.id}</span><h2>{selected.name}</h2><p>{selected.client} · {selected.site}</p></div><Status s={selected.status}/></div>
      <div className="money-row"><Metric label="Solicitado" value={money(selected.requested)}/><Metric label="Cálculo ABM" value={money(selected.calculated)}/><Metric label="Diferencia" value={money(Math.abs(selected.requested-selected.calculated))}/></div>
      <div className="checks"><Check ok text="Empleado localizado"/><Check ok text="Regla vigente encontrada en matriz"/><Check ok text="Asignación localizada"/><Check ok={selected.matched===selected.days} warn={selected.matched!==selected.days} text={selected.days?selected.matched+" de "+selected.days+" asistencias coinciden":"Asistencia no requerida"}/><Check ok={selected.support} warn={!selected.support} text={selected.support?"Respaldo encontrado":"Falta respaldo documental"}/></div>
      <div className="evidence"><button onClick={()=>setEvidence("asistencia")}><Eye/> Ver asistencia</button><button onClick={()=>setEvidence("matriz")}><Database/> Ver matriz</button><button onClick={()=>setEvidence("soporte")}><FileText/> Ver soporte</button></div>
      {evidence&&<EvidencePanel type={evidence} bonus={selected} close={()=>setEvidence(null)}/>} 
      <label className="comment">Justificación / comentario<textarea value={justification} onChange={e=>setJustification(e.target.value)} placeholder="Obligatorio cuando el monto autorizado difiere del solicitado o se acepta sin soporte."/></label>
      <div className="decision"><button onClick={()=>selected.support||justification.trim()?decide("Aprobado",!selected.support):setNotice("Captura una justificación para aceptar el bono sin soporte.")}><CheckCircle2/> Aprobar {money(selected.calculated)}</button><button className="secondary" onClick={()=>decide("Revisión")}><AlertTriangle/> Ajustar</button><button className="danger" onClick={()=>decide("Rechazado")}><XCircle/> Rechazar y devolver a ABM</button></div>
      <div className="close-validation"><span><b>{allResolved?"Todos los movimientos tienen decisión":"Aún existen excepciones pendientes"}</b><small>{allResolved?"El periodo puede pasar a la generación del layout.":"Resuelve cada excepción o autorízala con justificación."}</small></span>{!closed?<button disabled={!allResolved||role==="Usuario"} onClick={()=>{setClosed(true);setNotice("Validación cerrada. Periodo disponible para Layout Human.")}}><LockKeyhole/> Cerrar validación</button>:role==="Super Admin"&&<button className="secondary" onClick={()=>{if(!justification.trim()){setNotice("Captura una justificación para reabrir el ciclo.");return}setClosed(false);setExtension(v=>v+1);setNotice("Ciclo reabierto por Frances como versión extraordinaria.")}}><RotateCcw/> Reabrir ciclo</button>}</div>
     </div>
    </div></section>}
   {view==="matriz"&&<section className="screen"><Head title="Matriz de Bonos" text="Catálogo maestro versionado. En producción se cargará la matriz autorizada y sus reglas."/><div className="toolbar"><button><Upload/> Actualizar matriz</button><button className="secondary">Nuevo bono</button></div><table><thead><tr><th>Bono</th><th>Cliente / instalación</th><th>Tipo</th><th>Periodicidad</th><th>Validación</th><th>Estado</th></tr></thead><tbody><tr><td>Ayuda de transporte</td><td>Henkel · Salamanca</td><td>NETO</td><td>Semanal</td><td>Asistencia + instalación</td><td><Status s="Cumple"/></td></tr><tr><td>Acciones destacadas</td><td>General</td><td>BRUTO</td><td>Según solicitud</td><td>Soporte + autorización</td><td><Status s="Cumple"/></td></tr><tr><td>Asistencia</td><td>Según matriz</td><td>BRUTO</td><td>Semana vencida</td><td>Asistencia + incidencias</td><td><Status s="Revisión"/></td></tr></tbody></table></section>}
   {view==="historico"&&<section className="screen"><Head title="Histórico de Bonos" text="Consulta por empleado, periodo, cliente, instalación, bono y monto."/><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Buscar empleado o concepto"/></div><button><Download/> Exportar Excel</button></div><BonusTable data={records} open={(b)=>{setSelected(b);go("validacion")}}/></section>}
   {view==="conciliacion"&&<section className="screen"><Head title="Conciliación" text="Correo recibido vs. solicitud registrada vs. entrega a Nóminas vs. soporte."/><div className="kpis"><Kpi label="Detectadas" value="12" sub="Correo"/><Kpi label="Registradas" value="12" sub="Plataforma"/><Kpi label="Entregadas" value="10" sub="Nóminas"/><Kpi label="Con respaldo" value="9/10" sub="Documentos"/></div><Card title="Pendientes por conciliar"><p><b>2 solicitudes</b> detectadas todavía no han sido entregadas a Nóminas.</p><p><b>1 solicitud</b> entregada no tiene respaldo asociado.</p></Card></section>}
   {view==="layout"&&<section className="screen"><Head title="Layout Human" text="Sólo movimientos aprobados; Miriam asigna manualmente el lote del proceso de nómina."/><div className="kpis"><Kpi label="Aprobados" value={records.filter(b=>["Cumple","Aprobado"].includes(b.status)).length} sub="Listos"/><Kpi label="Excluidos" value={records.filter(b=>!["Cumple","Aprobado"].includes(b.status)).length} sub="Con observaciones"/><Kpi label="Lote" value="SEM38-01" sub="Asignación manual"/><Kpi label="Estructura" value="20 cols." sub="TXT · ISO-8859-1"/></div><Card title="Vista previa"><label className="lot-field">Identificador de lote Human<input defaultValue="SEM38-01"/></label><pre className="preview">5280 ⇥ 258760 ⇥ ∅ ⇥ BONO ASISTENCIA ⇥ 258760 ⇥ ∅ ⇥ ... ⇥ 900.00 ⇥ ... ⇥ SEM38-01{"\n"}5170 ⇥ 274816 ⇥ ∅ ⇥ AYUDA TRANSPORTE ⇥ 274816 ⇥ ∅ ⇥ ... ⇥ 500.00 ⇥ ... ⇥ ∅</pre><button disabled={!closed} onClick={()=>setNotice("TXT Human generado: 20 columnas, tabuladores, CRLF e ISO-8859-1.")}>Generar TXT {closed?"":"· cierre pendiente"}</button></Card></section>}
   {view==="admin"&&<section className="screen"><Head title="Administración" text="Frances puede agregar usuarios, cambiar roles o retirar accesos desde este panel."/><div className="grid2"><Card title="Usuarios"><button className="add-user" onClick={()=>setUsers(current=>[...current,{id:Date.now(),name:`Usuario ABM ${String(current.length).padStart(2,"0")}`,role:"Usuario"}])}><UserPlus/> Agregar usuario</button>{users.map(user=><User key={user.id} name={user.name} role={user.role} editable={role==="Super Admin"} onRole={next=>setUsers(current=>current.map(item=>item.id===user.id?{...item,role:next}:item))} onRemove={()=>setUsers(current=>current.filter(item=>item.id!==user.id))}/>)}</Card><Card title="Permisos"><p><b>Super Admin</b> · usuarios, configuración, periodos, reapertura y auditoría.</p><p><b>Admin</b> · operación, validación, excepciones y layouts.</p><p><b>Usuario</b> · carga, consulta y entrega de solicitudes.</p></Card></div></section>}
  </section>
 </main>
}
function Head({title,text}:{title:string;text:string}){return <div className="section-head"><div><h2>{title}</h2><p>{text}</p></div><span className="demo">PROTOTIPO UX · DATOS DEMO</span></div>}
function Kpi({label,value,sub}:{label:string;value:string|number;sub:string}){return <article className="kpi"><span>{label}</span><strong>{value}</strong><small>{sub}</small></article>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="card"><h3>{title}</h3>{children}</section>}
function Step({text,ok,warn}:{text:string;ok?:boolean;warn?:boolean}){return <div className={"step "+(ok?"ok":warn?"warn":"")}><span></span>{text}</div>}
function Status({s}:{s:Bonus["status"]}){return <span className={"status "+(["Cumple","Aprobado"].includes(s)?"green":s==="Revisión"?"amber":"red")}>{s}</span>}
function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Check({text,ok,warn}:{text:string;ok?:boolean;warn?:boolean}){return <div className={"check "+(ok?"ok":warn?"warn":"")} >{ok?<CheckCircle2/>:<AlertTriangle/>}<span>{text}</span></div>}
function BonusTable({data,open}:{data:Bonus[];open:(b:Bonus)=>void}){return <div className="table-wrap"><table><thead><tr><th>Empleado</th><th>Bono</th><th>Cliente / instalación</th><th>Solicitado</th><th>Respaldo</th><th>Resultado</th><th></th></tr></thead><tbody>{data.map(b=><tr key={b.id}><td><b>{b.name}</b><small>{b.employee}</small></td><td>{b.bonus}</td><td>{b.client}<small>{b.site}</small></td><td>{money(b.requested)}</td><td>{b.support?"Sí":"No"}</td><td><Status s={b.status}/></td><td><button className="mini" onClick={()=>open(b)}>Revisar</button></td></tr>)}</tbody></table></div>}
function EvidencePanel({type,bonus,close}:{type:"asistencia"|"matriz"|"soporte";bonus:Bonus;close:()=>void}){return <div className="modal-backdrop" onClick={close}><section className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">EVIDENCIA · {bonus.id}</span><h3>{type==="asistencia"?"Asistencia e instalación":type==="matriz"?"Regla de Matriz de Bonos":"Soporte documental"}</h3></div><button className="close" onClick={close}>×</button></div>{type==="asistencia"&&<><div className="evidence-summary"><Metric label="Empleado" value={bonus.employee}/><Metric label="Coincidencias" value={bonus.days?bonus.matched+" / "+bonus.days:"N/A"}/><Metric label="Instalación" value={bonus.site}/></div><table><thead><tr><th>Día</th><th>Instalación observada</th><th>Incidencia</th><th>Resultado</th></tr></thead><tbody>{["Lun","Mar","Mié","Jue","Vie"].slice(0,bonus.days||5).map((d,i)=><tr key={d}><td>{d}</td><td>{i<bonus.matched?bonus.site:"Instalación distinta / sin registro"}</td><td>{i<bonus.matched?"ASISTENCIA":"REVISAR"}</td><td><Status s={i<bonus.matched?"Cumple":"Revisión"}/></td></tr>)}</tbody></table><p className="source-note">Vista demo de la evidencia que ABM consultará en ICON. Para esta validación UX se simula con la estructura real de asistencia.</p></>}{type==="matriz"&&<><div className="rule-card"><span>BONO</span><b>{bonus.bonus}</b><span>CLIENTE / INSTALACIÓN</span><b>{bonus.client} · {bonus.site}</b><span>TIPO DE IMPORTE</span><b>{bonus.bonus.toLowerCase().includes("transporte")?"NETO":"BRUTO"}</b><span>REGLA DE VALIDACIÓN</span><b>{bonus.bonus.toLowerCase().includes("transporte")?"Asistencia + instalación + días trabajados":"Soporte + autorización + vigencia"}</b><span>IMPORTE CALCULADO</span><b>{money(bonus.calculated)}</b></div><p className="source-note">Vista demo de la regla vigente. En la fase de integración se mostrará la versión exacta de la Matriz de Bonos utilizada.</p></>}{type==="soporte"&&<>{bonus.support?<div className="document-preview"><FileText size={42}/><div><b>Soporte_{bonus.employee}_{bonus.id}.pdf</b><p>Documento asociado a la solicitud · Demo UX</p></div><button onClick={()=>setNotice("Demo: apertura del PDF se conectará al archivo real en SharePoint.")}><Eye/> Vista previa</button></div>:<div className="missing-support"><AlertTriangle size={36}/><h4>No se encontró respaldo documental</h4><p>Este movimiento debe solicitar evidencia antes de aprobarse.</p><button onClick={()=>{setNotice("Demo: solicitud de soporte registrada para "+bonus.name);close()}}>Solicitar soporte</button></div>}</>}<div className="modal-actions"><button className="secondary" onClick={close}>Cerrar</button></div></section></div>}
function User({name,role,editable,onRole,onRemove}:{name:string;role:Role;editable:boolean;onRole:(role:Role)=>void;onRemove:()=>void}){return <div className="user-row"><div className="avatar">{name.slice(0,2).toUpperCase()}</div><span><b>{name}</b><small>{role}</small></span>{editable&&<><label className="inline-role"><Pencil size={13}/><select value={role} onChange={e=>onRole(e.target.value as Role)}><option>Super Admin</option><option>Admin</option><option>Usuario</option></select></label><button className="mini danger-icon" title="Retirar acceso" onClick={onRemove}><Trash2 size={14}/></button></>}</div>}
