"use client";
import { useMemo, useState } from "react";
import { LayoutDashboard, Inbox, ShieldCheck, Database, History, GitCompareArrows, FileText, Users, Search, CheckCircle2, AlertTriangle, XCircle, Eye, CalendarClock, Upload, Download, ChevronRight } from "lucide-react";

type View="inicio"|"bandeja"|"validacion"|"matriz"|"historico"|"conciliacion"|"layout"|"admin";
type Bonus={id:string;employee:string;name:string;bonus:string;client:string;site:string;requested:number;calculated:number;support:boolean;status:"Cumple"|"Revisión"|"Falta evidencia";days:number;matched:number};
// UX Semana 38 publicado en GitHub Pages
const bonuses:Bonus[]=[
{id:"B-038-001",employee:"274816",name:"Julio César Martínez",bonus:"Ayuda de transporte",client:"Henkel",site:"Salamanca",requested:600,calculated:500,support:true,status:"Revisión",days:5,matched:4},
{id:"B-038-002",employee:"258760",name:"Omar Espinoza Díaz",bonus:"Asistencia",client:"Operación semanal",site:"Morelia",requested:900,calculated:900,support:true,status:"Cumple",days:5,matched:5},
{id:"B-038-003",employee:"253333",name:"Karla Vibriezca",bonus:"Acciones destacadas",client:"Cliente demo",site:"CDMX",requested:1200,calculated:1200,support:false,status:"Falta evidencia",days:0,matched:0},
{id:"B-038-004",employee:"261904",name:"Mariana Reyes",bonus:"Ayuda de transporte",client:"BBVA",site:"Saltillo",requested:500,calculated:540,support:true,status:"Revisión",days:5,matched:5},
];
const money=(n:number)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0}).format(n);
const nav=[["inicio","Resumen",LayoutDashboard],["bandeja","Bandeja de bonos",Inbox],["validacion","Centro de validación",ShieldCheck],["matriz","Matriz de bonos",Database],["historico","Histórico",History],["conciliacion","Conciliación",GitCompareArrows],["layout","Layout Human",FileText],["admin","Administración",Users]] as const;
export default function Page(){
 const [view,setView]=useState<View>("inicio"); const [selected,setSelected]=useState<Bonus>(bonuses[0]); const [notice,setNotice]=useState("");
 const totals=useMemo(()=>({amount:bonuses.reduce((a,b)=>a+b.requested,0),review:bonuses.filter(b=>b.status==="Revisión").length,support:bonuses.filter(b=>b.support).length}),[]);
 const go=(v:View)=>{setView(v);setNotice("")};
 return <main className="shell">
  <aside className="sidebar"><div className="brand"><div className="mark">IC</div><div><strong>Bonos Nómina</strong><small>INTER-CON · México</small></div></div>
   <nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?"active":""} onClick={()=>go(id as View)}><Icon size={18}/>{label}</button>)}</nav>
   <div className="user"><div className="avatar">FF</div><div><strong>Frances Fernández</strong><small>Super Admin · Demo UX</small></div></div>
  </aside>
  <section className="workspace">
   <header className="top"><div><small>Automatización de Bonos</small><h1>{nav.find(n=>n[0]===view)?.[1]}</h1></div><div className="period"><CalendarClock size={18}/><span><b>SEM II 38</b><small>Cierre lunes · 14:00</small></span></div></header>
   {notice&&<div className="notice">{notice}</div>}
   {view==="inicio"&&<section className="screen">
    <div className="hero"><div><span className="eyebrow">PERIODO ACTIVO</span><h2>Semana 38 · Validación de bonos</h2><p>Prototipo funcional para validar el flujo antes de conectar ICON, correo, SharePoint y Human.</p></div><button onClick={()=>go("bandeja")}>Abrir bandeja <ChevronRight size={18}/></button></div>
    <div className="kpis"><Kpi label="Movimientos" value="236" sub="Layout semanal"/><Kpi label="Importe demo" value={money(totals.amount)} sub="Muestra UX"/><Kpi label="Requieren revisión" value={totals.review} sub="Casos demo"/><Kpi label="Con respaldo" value={totals.support+"/4"} sub="Documentación"/></div>
    <div className="grid2"><Card title="Estado del periodo"><div className="steps"><Step ok text="Carga recibida"/><Step ok text="Entregado a Nóminas"/><Step warn text="Validación en curso"/><Step text="Layout Human"/><Step text="Cierre"/></div></Card><Card title="Alertas operativas"><AlertTriangle/><p><b>2 movimientos</b> presentan diferencias entre lo solicitado y la evidencia.</p><p><b>1 movimiento</b> no cuenta con respaldo.</p><button className="link" onClick={()=>go("validacion")}>Ir al Centro de Validación</button></Card></div>
   </section>}
   {view==="bandeja"&&<section className="screen"><Head title="Bandeja Semana 38" text="Lo entregado a Nóminas queda congelado para revisión; los ajustes posteriores requieren extensión."/><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Empleado, bono, cliente o instalación"/></div><button className="secondary" onClick={()=>setNotice("Demo: extensión de periodo solicitada.")}>Crear extensión</button><button onClick={()=>setNotice("Demo: periodo marcado como entregado a Nóminas.")}>Entregar a Nóminas</button></div><BonusTable data={bonuses} open={(b)=>{setSelected(b);go("validacion")}}/></section>}
   {view==="validacion"&&<section className="screen"><Head title="Centro de Validación" text="Solicitud, matriz, asignación, asistencia y respaldo en una sola decisión."/>
    <div className="validation">
     <div className="case-list">{bonuses.map(b=><button className={selected.id===b.id?"case active": "case"} onClick={()=>setSelected(b)} key={b.id}><span><b>{b.name}</b><small>{b.employee} · {b.bonus}</small></span><Status s={b.status}/></button>)}</div>
     <div className="case-detail"><div className="case-head"><div><span className="eyebrow">{selected.id}</span><h2>{selected.name}</h2><p>{selected.client} · {selected.site}</p></div><Status s={selected.status}/></div>
      <div className="money-row"><Metric label="Solicitado" value={money(selected.requested)}/><Metric label="Cálculo ABM" value={money(selected.calculated)}/><Metric label="Diferencia" value={money(Math.abs(selected.requested-selected.calculated))}/></div>
      <div className="checks"><Check ok text="Empleado localizado"/><Check ok text="Regla vigente encontrada en matriz"/><Check ok text="Asignación localizada"/><Check ok={selected.matched===selected.days} warn={selected.matched!==selected.days} text={selected.days?selected.matched+" de "+selected.days+" asistencias coinciden":"Asistencia no requerida"}/><Check ok={selected.support} warn={!selected.support} text={selected.support?"Respaldo encontrado":"Falta respaldo documental"}/></div>
      <div className="evidence"><button><Eye/> Ver asistencia</button><button><Database/> Ver matriz</button><button><FileText/> Ver soporte</button></div>
      <label className="comment">Justificación / comentario<textarea placeholder="Obligatorio cuando el monto autorizado difiere del solicitado."/></label>
      <div className="decision"><button onClick={()=>setNotice("Demo: movimiento aprobado por "+money(selected.calculated))}><CheckCircle2/> Aprobar {money(selected.calculated)}</button><button className="secondary" onClick={()=>setNotice("Demo: ajuste registrado para revisión.")}><AlertTriangle/> Ajustar</button><button className="danger" onClick={()=>setNotice("Demo: movimiento rechazado.")}><XCircle/> Rechazar</button></div>
     </div>
    </div></section>}
   {view==="matriz"&&<section className="screen"><Head title="Matriz de Bonos" text="Catálogo maestro versionado. En producción se cargará la matriz autorizada y sus reglas."/><div className="toolbar"><button><Upload/> Actualizar matriz</button><button className="secondary">Nuevo bono</button></div><table><thead><tr><th>Bono</th><th>Cliente / instalación</th><th>Tipo</th><th>Periodicidad</th><th>Validación</th><th>Estado</th></tr></thead><tbody><tr><td>Ayuda de transporte</td><td>Henkel · Salamanca</td><td>NETO</td><td>Semanal</td><td>Asistencia + instalación</td><td><Status s="Cumple"/></td></tr><tr><td>Acciones destacadas</td><td>General</td><td>BRUTO</td><td>Según solicitud</td><td>Soporte + autorización</td><td><Status s="Cumple"/></td></tr><tr><td>Asistencia</td><td>Según matriz</td><td>BRUTO</td><td>Semana vencida</td><td>Asistencia + incidencias</td><td><Status s="Revisión"/></td></tr></tbody></table></section>}
   {view==="historico"&&<section className="screen"><Head title="Histórico de Bonos" text="Consulta por empleado, periodo, cliente, instalación, bono y monto."/><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Buscar empleado o concepto"/></div><button><Download/> Exportar Excel</button></div><BonusTable data={bonuses} open={(b)=>{setSelected(b);go("validacion")}}/></section>}
   {view==="conciliacion"&&<section className="screen"><Head title="Conciliación" text="Correo recibido vs. solicitud registrada vs. entrega a Nóminas vs. soporte."/><div className="kpis"><Kpi label="Detectadas" value="12" sub="Correo"/><Kpi label="Registradas" value="12" sub="Plataforma"/><Kpi label="Entregadas" value="10" sub="Nóminas"/><Kpi label="Con respaldo" value="9/10" sub="Documentos"/></div><Card title="Pendientes por conciliar"><p><b>2 solicitudes</b> detectadas todavía no han sido entregadas a Nóminas.</p><p><b>1 solicitud</b> entregada no tiene respaldo asociado.</p></Card></section>}
   {view==="layout"&&<section className="screen"><Head title="Layout Human" text="Sólo movimientos aprobados. La generación real se habilita después de autorizar el UX."/><div className="kpis"><Kpi label="Aprobados" value="218" sub="Listos"/><Kpi label="Excluidos" value="18" sub="Con observaciones"/><Kpi label="Lote" value="SEM38-01" sub="Demo"/><Kpi label="Estructura" value="20 cols." sub="TXT"/></div><Card title="Vista previa"><pre className="preview">5280 ⇥ 258760 ⇥ BONO ASISTENCIA ⇥ ∅ ⇥ ∅ ⇥ ... ⇥ 900.00 ⇥ ... ⇥ SEM38-01{"\n"}5170 ⇥ 274816 ⇥ AYUDA TRANSPORTE ⇥ ∅ ⇥ ∅ ⇥ ... ⇥ 500.00 ⇥ ... ⇥ SEM38-01</pre><button disabled>Generar TXT · pendiente de autorización</button></Card></section>}
   {view==="admin"&&<section className="screen"><Head title="Administración" text="Gestión de usuarios y permisos para Super Admin."/><div className="grid2"><Card title="Usuarios"><User name="Frances Fernández" role="Super Admin"/><User name="Miriam" role="Admin"/><User name="Lizbeth" role="Admin"/><User name="Usuario ABM" role="Usuario"/></Card><Card title="Permisos"><p>Super Admin · usuarios, configuración, periodos y auditoría.</p><p>Admin · operación, validación, ajustes y layouts.</p><p>Usuario · carga, consulta y entrega de solicitudes.</p></Card></div></section>}
  </section>
 </main>
}
function Head({title,text}:{title:string;text:string}){return <div className="section-head"><div><h2>{title}</h2><p>{text}</p></div><span className="demo">PROTOTIPO UX · DATOS DEMO</span></div>}
function Kpi({label,value,sub}:{label:string;value:string|number;sub:string}){return <article className="kpi"><span>{label}</span><strong>{value}</strong><small>{sub}</small></article>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="card"><h3>{title}</h3>{children}</section>}
function Step({text,ok,warn}:{text:string;ok?:boolean;warn?:boolean}){return <div className={"step "+(ok?"ok":warn?"warn":"")}><span></span>{text}</div>}
function Status({s}:{s:Bonus["status"]}){return <span className={"status "+(s==="Cumple"?"green":s==="Revisión"?"amber":"red")}>{s}</span>}
function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Check({text,ok,warn}:{text:string;ok?:boolean;warn?:boolean}){return <div className={"check "+(ok?"ok":warn?"warn":"")} >{ok?<CheckCircle2/>:<AlertTriangle/>}<span>{text}</span></div>}
function BonusTable({data,open}:{data:Bonus[];open:(b:Bonus)=>void}){return <div className="table-wrap"><table><thead><tr><th>Empleado</th><th>Bono</th><th>Cliente / instalación</th><th>Solicitado</th><th>Respaldo</th><th>Resultado</th><th></th></tr></thead><tbody>{data.map(b=><tr key={b.id}><td><b>{b.name}</b><small>{b.employee}</small></td><td>{b.bonus}</td><td>{b.client}<small>{b.site}</small></td><td>{money(b.requested)}</td><td>{b.support?"Sí":"No"}</td><td><Status s={b.status}/></td><td><button className="mini" onClick={()=>open(b)}>Revisar</button></td></tr>)}</tbody></table></div>}
function User({name,role}:{name:string;role:string}){return <div className="user-row"><div className="avatar">{name.slice(0,2).toUpperCase()}</div><span><b>{name}</b><small>{role}</small></span><button className="mini">Editar</button></div>}
